source 'https://rubygems.org'
#gem "jekyll-theme-example"

group :jekyll_plugins do	
	gem "github-pages"
	gem "jekyll-theme-slate"
	gem "jekyll-last-modified-at"
end

gem "faraday-retry"
gem "bigdecimal"
gem "csv"
