source 'https://rubygems.org'
#gem "jekyll-theme-example"

group :jekyll_plugins do	
	gem "github-pages"
	gem "jekyll-theme-slate"
#	gem "jekyll-pdf-embed"
end

gem "faraday-retry"
gem "csv"
gem "bigdecimal"
