source 'https://rubygems.org'
#gem "jekyll-theme-example"
gem "jekyll-theme-slate"
gem "github-pages", group: :jekyll_plugins
gem "jekyll-pdf-embed", group: :jekyll_plugins
# group :jekyll_plugins do	
#end
gem "csv"
